title: dick.codes
domain: dick.codes
url: https://dick.codes
exclude: ['bin/', 'package.json', 'package-lock.json', 'postcss.config.js', 'tailwind.config.js']
baseurl:
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll/minibundle
  - jekyll-postcss
  - jekyll-sitemap
postcss:
  cache: false
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 100
    css: class
webmentions:
  username: dick.codes
