title: dick.codes
domain: dick.codes
url: https://dick.codes
exclude: ['bin/', 'README.md', 'LICENSE.txt']
include: ['_pages']
baseurl:
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-sitemap
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 100
    css: class
